//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace osum.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class General {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal General() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("osum.Resources.General", typeof(General).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accuracy.
        /// </summary>
        internal static string Accuracy {
            get {
                return ResourceManager.GetString("Accuracy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avg. Timing: .
        /// </summary>
        internal static string AvgTiming {
            get {
                return ResourceManager.GetString("AvgTiming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combo.
        /// </summary>
        internal static string Combo {
            get {
                return ResourceManager.GetString("Combo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download more songs....
        /// </summary>
        internal static string DownloadMoreSongs {
            get {
                return ResourceManager.GetString("DownloadMoreSongs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while downloading song listing..
        /// </summary>
        internal static string ErrorWhileDownloadingSongListing {
            get {
                return ResourceManager.GetString("ErrorWhileDownloadingSongListing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have all available packs.\nCheck back later!.
        /// </summary>
        internal static string HaveAllAvailableSongPacks {
            get {
                return ResourceManager.GetString("HaveAllAvailableSongPacks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hit.
        /// </summary>
        internal static string Hit {
            get {
                return ResourceManager.GetString("Hit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Combo.
        /// </summary>
        internal static string MaxCombo {
            get {
                return ResourceManager.GetString("MaxCombo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score.
        /// </summary>
        internal static string Score {
            get {
                return ResourceManager.GetString("Score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spin.
        /// </summary>
        internal static string Spin {
            get {
                return ResourceManager.GetString("Spin", resourceCulture);
            }
        }
    }
}
