//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace osum.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Tutorial {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Tutorial() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("osum.Resources.Tutorial", typeof(Tutorial).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ...and hold until the circle explodes!.
        /// </summary>
        internal static string AndHoldUntilTheCircleExplodes {
            get {
                return ResourceManager.GetString("AndHoldUntilTheCircleExplodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations. You now have the skills required to challenge osu!.
        /// </summary>
        internal static string Completion {
            get {
                return ResourceManager.GetString("Completion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Easy....
        /// </summary>
        internal static string Easy {
            get {
                return ResourceManager.GetString("Easy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fingers.
        /// </summary>
        internal static string Fingers {
            get {
                return ResourceManager.GetString("Fingers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good....
        /// </summary>
        internal static string Good {
            get {
                return ResourceManager.GetString("Good", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Great!.
        /// </summary>
        internal static string Great {
            get {
                return ResourceManager.GetString("Great", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hard....
        /// </summary>
        internal static string Hard {
            get {
                return ResourceManager.GetString("Hard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The health bar is located at the top-left of your display..
        /// </summary>
        internal static string Healthbar1 {
            get {
                return ResourceManager.GetString("Healthbar1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It will go up or down depending on your performance..
        /// </summary>
        internal static string Healthbar2 {
            get {
                return ResourceManager.GetString("Healthbar2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In stream mode gameplay, you can jump to the next stream by filling your health bar..
        /// </summary>
        internal static string Healthbar3 {
            get {
                return ResourceManager.GetString("Healthbar3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In a similar manner, if it reaches zero, you will drop down a stream..
        /// </summary>
        internal static string Healthbar4 {
            get {
                return ResourceManager.GetString("Healthbar4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If it hits zero on the lowest stream you will fail instantly, so watch out!.
        /// </summary>
        internal static string Healthbar5 {
            get {
                return ResourceManager.GetString("Healthbar5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Hit circles&quot; are the most basic beat in osu!..
        /// </summary>
        internal static string HitCircle1 {
            get {
                return ResourceManager.GetString("HitCircle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to They are made up of the main circle....
        /// </summary>
        internal static string HitCircle2 {
            get {
                return ResourceManager.GetString("HitCircle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And the approach circle..
        /// </summary>
        internal static string HitCircle3 {
            get {
                return ResourceManager.GetString("HitCircle3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When the approach circle reaches the border of the main circle....
        /// </summary>
        internal static string HitCircle4 {
            get {
                return ResourceManager.GetString("HitCircle4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ...you should tap!.
        /// </summary>
        internal static string HitCircle4_1 {
            get {
                return ResourceManager.GetString("HitCircle4_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The more accurate your timing, the more points you get!.
        /// </summary>
        internal static string HitCircle5 {
            get {
                return ResourceManager.GetString("HitCircle5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Okay. Let&apos;s give it a shot!
        ///Try hitting these 8 hit circles..
        /// </summary>
        internal static string HitCircle6 {
            get {
                return ResourceManager.GetString("HitCircle6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hmm, looks like we need to practise a bit more. Let&apos;s go over this again!.
        /// </summary>
        internal static string HitCircleJudge1 {
            get {
                return ResourceManager.GetString("HitCircleJudge1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting there!
        ///Watch the approaching circle carefully and listen to the beat. Let&apos;s try once more!.
        /// </summary>
        internal static string HitCircleJudge2 {
            get {
                return ResourceManager.GetString("HitCircleJudge2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That&apos;s right!
        ///Focus on the beat of the song and try to time your taps to get higher accuracy..
        /// </summary>
        internal static string HitCircleJudge3 {
            get {
                return ResourceManager.GetString("HitCircleJudge3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flawless! Great job!.
        /// </summary>
        internal static string HitCircleJudge4 {
            get {
                return ResourceManager.GetString("HitCircleJudge4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Holds&quot; are like hit circles, but you need to tap....
        /// </summary>
        internal static string Hold1 {
            get {
                return ResourceManager.GetString("Hold1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let&apos;s try a few holds!.
        /// </summary>
        internal static string Hold2 {
            get {
                return ResourceManager.GetString("Hold2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now with two fingers!.
        /// </summary>
        internal static string Hold3 {
            get {
                return ResourceManager.GetString("Hold3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make sure you hold the notes until they explode! Let&apos;s go over the basics again..
        /// </summary>
        internal static string HoldJudge1 {
            get {
                return ResourceManager.GetString("HoldJudge1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeah, just like that. Make sure to hold them until they explode!.
        /// </summary>
        internal static string HoldJudge2 {
            get {
                return ResourceManager.GetString("HoldJudge2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to osu!stream is a game which requires both rhythmical and positional accuracy..
        /// </summary>
        internal static string Introduction2 {
            get {
                return ResourceManager.GetString("Introduction2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will need to feel the beat, so make sure you are using headphones or playing in quiet surroundings!.
        /// </summary>
        internal static string Introduction3 {
            get {
                return ResourceManager.GetString("Introduction3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let&apos;s start by looking at the different kinds of beats..
        /// </summary>
        internal static string Introduction4 {
            get {
                return ResourceManager.GetString("Introduction4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some beats need to be hit at the same time..
        /// </summary>
        internal static string Multitouch1 {
            get {
                return ResourceManager.GetString("Multitouch1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will be denoted by a line connecting the beats..
        /// </summary>
        internal static string Multitouch1_1 {
            get {
                return ResourceManager.GetString("Multitouch1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Levels are made to be playable with two {0}, but you will need to decide which fingers to use for each beat!.
        /// </summary>
        internal static string Multitouch2 {
            get {
                return ResourceManager.GetString("Multitouch2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let&apos;s try some connected beats!.
        /// </summary>
        internal static string Multitouch3 {
            get {
                return ResourceManager.GetString("Multitouch3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make sure to touch both circles at the same time. Watch closely!.
        /// </summary>
        internal static string MultitouchJudge1 {
            get {
                return ResourceManager.GetString("MultitouchJudge1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pretty good..
        /// </summary>
        internal static string MultitouchJudge2 {
            get {
                return ResourceManager.GetString("MultitouchJudge2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve mastered it..
        /// </summary>
        internal static string MultitouchJudge3 {
            get {
                return ResourceManager.GetString("MultitouchJudge3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal....
        /// </summary>
        internal static string Normal {
            get {
                return ResourceManager.GetString("Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfect!.
        /// </summary>
        internal static string Perfect {
            get {
                return ResourceManager.GetString("Perfect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scoring is based on a your accuracy and combo..
        /// </summary>
        internal static string Score1 {
            get {
                return ResourceManager.GetString("Score1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can also get score bonuses from reaching higher streams, and for spinning spinners fast!.
        /// </summary>
        internal static string Score2 {
            get {
                return ResourceManager.GetString("Score2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your current combo can be seen in the bottom-left corner of the screen..
        /// </summary>
        internal static string Score3 {
            get {
                return ResourceManager.GetString("Score3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your combo will only show up when you are on a streak!.
        /// </summary>
        internal static string Score4 {
            get {
                return ResourceManager.GetString("Score4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Sliders&quot; are like hit circles,.
        /// </summary>
        internal static string Slider1 {
            get {
                return ResourceManager.GetString("Slider1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to but extend into tracks..
        /// </summary>
        internal static string Slider1_1 {
            get {
                return ResourceManager.GetString("Slider1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Touch it like a circle....
        /// </summary>
        internal static string Slider2 {
            get {
                return ResourceManager.GetString("Slider2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to then follow the ball with your finger to the end!.
        /// </summary>
        internal static string Slider2_1 {
            get {
                return ResourceManager.GetString("Slider2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some sliders need to be repeated..
        /// </summary>
        internal static string Slider3 {
            get {
                return ResourceManager.GetString("Slider3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sometimes you will need to repeat more than once..
        /// </summary>
        internal static string Slider3_1 {
            get {
                return ResourceManager.GetString("Slider3_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will be indicated by an arrow at the end..
        /// </summary>
        internal static string Slider3_2 {
            get {
                return ResourceManager.GetString("Slider3_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let&apos;s try some sliders!.
        /// </summary>
        internal static string Slider4 {
            get {
                return ResourceManager.GetString("Slider4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make sure you follow the ball with your finger! Let&apos;s go over the basics again..
        /// </summary>
        internal static string SliderJudge1 {
            get {
                return ResourceManager.GetString("SliderJudge1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make sure you follow the ball with your finger! Let&apos;s try once more..
        /// </summary>
        internal static string SliderJudge2 {
            get {
                return ResourceManager.GetString("SliderJudge2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeah, just like that. Make sure to watch and follow the ball!.
        /// </summary>
        internal static string SliderJudge3 {
            get {
                return ResourceManager.GetString("SliderJudge3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Spinners&quot; are the only beats which are not rhythmical..
        /// </summary>
        internal static string Spinner1 {
            get {
                return ResourceManager.GetString("Spinner1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When a spinner appears....
        /// </summary>
        internal static string Spinner2 {
            get {
                return ResourceManager.GetString("Spinner2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..you should spin it with your finger until the bars fill!.
        /// </summary>
        internal static string Spinner2_1 {
            get {
                return ResourceManager.GetString("Spinner2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spin faster for a bonus!.
        /// </summary>
        internal static string Spinner3 {
            get {
                return ResourceManager.GetString("Spinner3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to But make sure you are ready for the beats after the spinner!.
        /// </summary>
        internal static string Spinner3_1 {
            get {
                return ResourceManager.GetString("Spinner3_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let&apos;s try some spinners!.
        /// </summary>
        internal static string Spinner4 {
            get {
                return ResourceManager.GetString("Spinner4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you actually trying? All you need to do is make circles with your finger! Let&apos;s try again....
        /// </summary>
        internal static string SpinnerJudge1 {
            get {
                return ResourceManager.GetString("SpinnerJudge1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re spinning, but a bit slow. Let&apos;s try once more!.
        /// </summary>
        internal static string SpinnerJudge2 {
            get {
                return ResourceManager.GetString("SpinnerJudge2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You spin like a TORNADO!.
        /// </summary>
        internal static string SpinnerJudge3 {
            get {
                return ResourceManager.GetString("SpinnerJudge3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beats can also appear in a stack on top of each other..
        /// </summary>
        internal static string Stacked1 {
            get {
                return ResourceManager.GetString("Stacked1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watch for multiple approach circles and tap in time with them..
        /// </summary>
        internal static string Stacked1_1 {
            get {
                return ResourceManager.GetString("Stacked1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hit circles can also be stacked at the beginning of sliders, so watch out for those!.
        /// </summary>
        internal static string Stacked2 {
            get {
                return ResourceManager.GetString("Stacked2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let&apos;s try a few stacked beats!.
        /// </summary>
        internal static string Stacked3 {
            get {
                return ResourceManager.GetString("Stacked3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hmm, not quite.. Let&apos;s go over stacks again!.
        /// </summary>
        internal static string StackedJudge1 {
            get {
                return ResourceManager.GetString("StackedJudge1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watch the approach circles closely and make sure you hit every note in the stacks!.
        /// </summary>
        internal static string StackedJudge2 {
            get {
                return ResourceManager.GetString("StackedJudge2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good job!.
        /// </summary>
        internal static string StackedJudge3 {
            get {
                return ResourceManager.GetString("StackedJudge3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excellent!.
        /// </summary>
        internal static string StackedJudge4 {
            get {
                return ResourceManager.GetString("StackedJudge4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are three different modes of play..
        /// </summary>
        internal static string Stream1 {
            get {
                return ResourceManager.GetString("Stream1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream mode consists of three separate difficulties, otherwise known as &apos;Streams&apos;..
        /// </summary>
        internal static string Stream2 {
            get {
                return ResourceManager.GetString("Stream2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reaching higher streams will make gameplay harder, but allow you to get a higher score..
        /// </summary>
        internal static string Stream3 {
            get {
                return ResourceManager.GetString("Stream3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap to continue!.
        /// </summary>
        internal static string TapToContinue {
            get {
                return ResourceManager.GetString("TapToContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to thumbs.
        /// </summary>
        internal static string Thumbs {
            get {
                return ResourceManager.GetString("Thumbs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A bit early...
        /// </summary>
        internal static string TimingEarly {
            get {
                return ResourceManager.GetString("TimingEarly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A bit late...
        /// </summary>
        internal static string TimingLate {
            get {
                return ResourceManager.GetString("TimingLate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very early...
        /// </summary>
        internal static string TimingVeryEarly {
            get {
                return ResourceManager.GetString("TimingVeryEarly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very late...
        /// </summary>
        internal static string TimingVeryLate {
            get {
                return ResourceManager.GetString("TimingVeryLate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the world of osu!.
        ///This tutorial will teach you everything you need to know in order to become a rhythm master..
        /// </summary>
        internal static string WelcomeToTheWorldOfOsu {
            get {
                return ResourceManager.GetString("WelcomeToTheWorldOfOsu", resourceCulture);
            }
        }
    }
}
