namespace Un4seen.Bass
{
    using System;

    public enum BASSConfig
    {
        BASS_CONFIG_3DALGORITHM = 10,
        BASS_CONFIG_AC3_DYNRNG = 0x10001,
        BASS_CONFIG_BUFFER = 0,
        BASS_CONFIG_CD_AUTOSPEED = 0x10202,
        BASS_CONFIG_CD_FREEOLD = 0x10200,
        BASS_CONFIG_CD_RETRY = 0x10201,
        BASS_CONFIG_CD_SKIPERROR = 0x10203,
        BASS_CONFIG_CURVE_PAN = 8,
        BASS_CONFIG_CURVE_VOL = 7,
        BASS_CONFIG_ENCODE_CAST_TIMEOUT = 0x10310,
        BASS_CONFIG_ENCODE_PRIORITY = 0x10300,
        BASS_CONFIG_FLOATDSP = 9,
        BASS_CONFIG_GVOL_MUSIC = 6,
        BASS_CONFIG_GVOL_SAMPLE = 4,
        BASS_CONFIG_GVOL_STREAM = 5,
        BASS_CONFIG_MIDI_AUTOFONT = 0x10402,
        BASS_CONFIG_MIDI_COMPACT = 0x10400,
        BASS_CONFIG_MIDI_VOICES = 0x10401,
        BASS_CONFIG_MIXER_BUFFER = 0x10601,
        BASS_CONFIG_MIXER_FILTER = 0x10600,
        BASS_CONFIG_MUSIC_VIRTUAL = 0x16,
        BASS_CONFIG_NET_AGENT = 0x10,
        BASS_CONFIG_NET_BUFFER = 12,
        BASS_CONFIG_NET_PASSIVE = 0x12,
        BASS_CONFIG_NET_PLAYLIST = 0x15,
        BASS_CONFIG_NET_PREBUF = 15,
        BASS_CONFIG_NET_PROXY = 0x11,
        BASS_CONFIG_NET_TIMEOUT = 11,
        BASS_CONFIG_PAUSE_NOPLAY = 13,
        BASS_CONFIG_REC_BUFFER = 0x13,
        BASS_CONFIG_UPDATEPERIOD = 1,
        BASS_CONFIG_VERIFY = 0x17,
        BASS_CONFIG_WMA_BASSFILE = 0x10103,
        BASS_CONFIG_WMA_NETSEEK = 0x10104,
        BASS_CONFIG_WMA_PREBUF = 0x10101
    }
}

