namespace Un4seen.Bass
{
    using System;

    public enum BASSError
    {
        BASS_ERROR_ACM_CANCEL = 0x7d0,
        BASS_ERROR_ALREADY = 14,
        BASS_ERROR_BUFLOST = 4,
        BASS_ERROR_CAST_DENIED = 0x834,
        BASS_ERROR_CDTRACK = 13,
        BASS_ERROR_CODEC = 0x2c,
        BASS_ERROR_CREATE = 0x21,
        BASS_ERROR_DECODE = 0x26,
        BASS_ERROR_DEVICE = 0x17,
        BASS_ERROR_DRIVER = 3,
        BASS_ERROR_DX = 0x27,
        BASS_ERROR_EMPTY = 0x1f,
        BASS_ERROR_FILEFORM = 0x29,
        BASS_ERROR_FILEOPEN = 2,
        BASS_ERROR_FORMAT = 6,
        BASS_ERROR_FREQ = 0x19,
        BASS_ERROR_HANDLE = 5,
        BASS_ERROR_ILLPARAM = 20,
        BASS_ERROR_ILLTYPE = 0x13,
        BASS_ERROR_INIT = 8,
        BASS_ERROR_MEM = 1,
        BASS_ERROR_NO3D = 0x15,
        BASS_ERROR_NOCD = 12,
        BASS_ERROR_NOCHAN = 0x12,
        BASS_ERROR_NOEAX = 0x16,
        BASS_ERROR_NOFX = 0x22,
        BASS_ERROR_NOHW = 0x1d,
        BASS_ERROR_NONET = 0x20,
        BASS_ERROR_NOPAUSE = 0x10,
        BASS_ERROR_NOPLAY = 0x18,
        BASS_ERROR_NOTAUDIO = 0x11,
        BASS_ERROR_NOTAVAIL = 0x25,
        BASS_ERROR_NOTFILE = 0x1b,
        BASS_ERROR_PLAYING = 0x23,
        BASS_ERROR_POSITION = 7,
        BASS_ERROR_SPEAKER = 0x2a,
        BASS_ERROR_START = 9,
        BASS_ERROR_TIMEOUT = 40,
        BASS_ERROR_UNKNOWN = -1,
        BASS_ERROR_VERSION = 0x2b,
        BASS_ERROR_WMA_CODEC = 0x3eb,
        BASS_ERROR_WMA_DENIED = 0x3ea,
        BASS_ERROR_WMA_INDIVIDUAL = 0x3ec,
        BASS_ERROR_WMA_LICENSE = 0x3e8,
        BASS_ERROR_WMA_WM9 = 0x3e9,
        BASS_FX_ERROR_BPMINUSE = 0xfa1,
        BASS_FX_ERROR_NODECODE = 0xfa0,
        BASS_OK = 0,
        BASS_VST_ERROR_NOINPUTS = 0xbb8,
        BASS_VST_ERROR_NOOUTPUTS = 0xbb9,
        BASS_VST_ERROR_NOREALTIME = 0xbba
    }
}

