namespace Un4seen.Bass
{
    using System;

    public enum BASSAttribute
    {
        BASS_ATTRIB_EAXMIX = 4,
        BASS_ATTRIB_FREQ = 1,
        BASS_ATTRIB_MUSIC_AMPLIFY = 0x100,
        BASS_ATTRIB_MUSIC_BPM = 0x103,
        BASS_ATTRIB_MUSIC_PANSEP = 0x101,
        BASS_ATTRIB_MUSIC_PSCALER = 0x102,
        BASS_ATTRIB_MUSIC_SPEED = 260,
        BASS_ATTRIB_MUSIC_VOL_CHAN = 0x200,
        BASS_ATTRIB_MUSIC_VOL_GLOBAL = 0x105,
        BASS_ATTRIB_MUSIC_VOL_INST = 0x300,
        BASS_ATTRIB_PAN = 3,
        BASS_ATTRIB_REVERSE_DIR = 0x11000,
        BASS_ATTRIB_TEMPO = 0x10000,
        BASS_ATTRIB_TEMPO_FREQ = 0x10002,
        BASS_ATTRIB_TEMPO_OPTION_AA_FILTER_LENGTH = 0x10011,
        BASS_ATTRIB_TEMPO_OPTION_OVERLAP_MS = 0x10015,
        BASS_ATTRIB_TEMPO_OPTION_SEEKWINDOW_MS = 0x10014,
        BASS_ATTRIB_TEMPO_OPTION_SEQUENCE_MS = 0x10013,
        BASS_ATTRIB_TEMPO_OPTION_USE_AA_FILTER = 0x10010,
        BASS_ATTRIB_TEMPO_OPTION_USE_QUICKALGO = 0x10012,
        BASS_ATTRIB_TEMPO_PITCH = 0x10001,
        BASS_ATTRIB_VOL = 2
    }
}

